### ISSUE TITLE
Simplify testing by keeping installable copy of generated files in git

### ISSUE THREAD

**Issue by texasaggie97** [ni/nimi-python#1174]
# Background
Right now we keep a copy of the generated files in git in `$(ROOT_DIR)/generated/<driver>`. But, this copy is not installable since the files are not all in the correct relative positions.

We keep these files here for ease of validating any changes: We can see what, if anything, changed in the generated files for a given PR.

This also makes the build (and makefiles) more complicated in order to copy the generated files to the generated directory in addition to the location where they are actually built into.

# Proposal
Do not add the files in generated to git and instead, add a subset of the files generated into `bin`. This subset would be:
* `bin/<driver>/<driver>/**`
* `bin/<driver>/setup.py`
* `bin/<driver>/README.rst`

We would not add any of the generated wheels or sdist files.

# Benefit
There are a couple of benefits by doing this.
1. We know exactly what was tested since we are testing what is in git
1. The tests will run faster since we would not need to run the codegen step on every platform/python version we want to test
    1. We would build the wheel from the files in git for each platform/python version since we do want to test the wheel itself
1. Simplify the make files to no longer need the extra copy to generated.

**Comment by marcoskirsch** [comment]
So instead of copying generated files to `generated/` after code-generation, we'll just keep them in their original codegeneration location and add those to git.

I can see how this is confusing to someone looking at our repo:

* It is not clear that things inside `bin/` are source files
* It is not clear that on git only a subset of the files that are produced during a build are included.

I wonder if we can better show intent by playing around with the folder names/structure inside `bin/`.
