### ISSUE TITLE
Remove nitclk properties that need repeated capabilities

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#1221]
Two properties in NI-TClk need repeated capabilties.
We don't support that in `nitclk` so we will remove it. We don't think the use cases justify it.

The properties are:
* `NITCLK_ATTR_SCRIPT_TRIGGER_MASTER_SESSION`
* `NITCLK_ATTR_SEQUENCER_FLAG_MASTER_SESSION`

If a use case emerges where these are needed, we can reconsider solving the limitation.

**Comment by sbethur** [comment]
Turns out `NITCLK_ATTR_SEQUENCER_FLAG_MASTER_SESSION` is not repeated-capabilities-based. Even though there are 4 instances of Sequencer Flag in nidigital but they share the same trigger line.

There is another property - `NITCLK_ATTR_CONDITIONAL_JUMP_TRIGGER_MASTER_SESSION` that IS repeated-capabilities-based. But this property is missing from NI-TClk LabVIEW API (and hence missing in nimi-python). Created an internal bug (#962850) for it.
