### ISSUE TITLE
NI-DMM System tests fail on a simulated PCI-4070

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#152]
- test_get_dev_temp returns 0.0 and the test is looking for a range of 20-40
- test_multi_point_acquisition fails due to max time exceeded before operation completed on read_multi_point call.
- test_method_with_enum_output_type_method fails as "assert <AcquisitionStatus.NO_ACQUISITION_IN_PROGRESS: 4> == 4"

**Comment by marcoskirsch** [comment]
> test_get_dev_temp  returns 0.0 and the test is looking for a range of 20-40

I doubt this is the case on 408x.

> test_multi_point_acquisition fails due to max time exceeded before operation completed on read_multi_point call.

I doubt this is the case on 408x.

> test_method_with_enum_output_type_method fails as "assert <AcquisitionStatus.NO_ACQUISITION_IN_PROGRESS: 4> == 4"

I doubt this is the case on 408x.

**Comment by injaleea** [comment]
> test_get_dev_temp returns 0.0 and the test is looking for a range of 20-40

Simulated device always returned dev_temp as 0. right ? [ LabVIEW returns dev_temp = 0 for simulated devices ]

> test_multi_point_acquisition fails due to max time exceeded before operation completed on read_multi_point call.

Ideally **Maximum number of measurements = Trigger Count * Sample Count**. 
But for Simulated devices ,it looks like trigger happens only once ,
**ie,
Maximum number of measurement = Sample Count** [Noticed same behavior with LabVIEW APIs aswell. Should it be an issue on LabVIEW APIs aswell?] 

> test_method_with_enum_output_type_method fails as "assert <AcquisitionStatus.NO_ACQUISITION_IN_PROGRESS: 4> == 4"

https://github.com/ni/nimi-python/pull/151 should have fix for this issue

**Comment by marcoskirsch** [comment]
```
Simulated device always returned dev_temp as 0. right ?
[ LabVIEW returns dev_temp = 0 for simulated devices ]
```

It depends which device you are simulating.

```
But for Simulated devices ,it looks like trigger happens only once ,ie,
Maximum number of measurement = Sample Count
```

This also depends on which device you're simulating. I'm fairly confident you "receive" all triggers when you simulate a 408x. Not sure about others.

`[Noticed same behavior with LabVIEW APIs aswell. Should it be an issue on LabVIEW APIs aswell?]`

To be clear, the LabVIEW API, just like the Python bindings and the .NET wrappers simply call into the C API. Behaviors should be identical with few exceptions because they all call the same exact functions.
