### ISSUE TITLE
The return value of `get_date_and_time()` related function(s) across drivers should be consistently named

### ISSUE THREAD

**Issue by olsl21** [ni/nimi-python#1716]
### Description of issue

Currently, the return value of `get_date_and_time()` related function(s) is correctly named "last_cal_datetime" in NI-SCOPE, but incorrectly named "month" in NI-DCPower, NI-DMM, NI-FAKE and NI-FGEN. They should be made consistent.

This issue is mentioned in #1707.

**Comment by ni-jfitzger** [comment]
@marcoskirsch @tobiasgordon
The internal work item clued me in that this might already be fixed. An inspection of documentation for "get.*_date_and_time" methods in session.py files confirmed it. The issue was isolated to session.py; class.rst (Read the Docs documentation) is not part of it.

Closing this.
