### ISSUE TITLE
Remove hardware requirement from system tests by using simulation

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#192]
This allows system tests to run with the requirement of installing the driver runtime but no need for hardware availability.

This doesn't apply to NI-ModInst hardware tests.

**Comment by marcoskirsch** [comment]
This was @Fladolcetta 's idea, I think it's a good one.
* It lowers the barrier of entry for developers
* Does not affect test coverage, since system test responsibility ends once we verify that the underlying driver is called correctly at the ctypes level.
* It also gives us more control over what device model the tests are run on.
* Allows running unit tests on VMs

Awaiting @texasaggie97 opinion.

**Comment by texasaggie97** [comment]
I think this is a good idea.

One concern would be that some things need to simulate specific types of HW in order to test a specific feature, and this could end up with a mix of devices.

One way to fix this would be to have multiple test files: test_4080.py, test_4070.py, test_4065.py. This way the fixture in each of those files would open a simulated session to the specified device. Then tests which need specific HW would go in the appropriate file.
