### ISSUE TITLE
How we are handling ring controls ?

### ISSUE THREAD

**Issue by injaleea** [ni/nimi-python#540]
configure_digital_edge_start_trigger requires a parameter source which is a ring control(niFgen_ctl Trigger Source Values (Ring).ctl) in LabVIEW . This ring is not listed anywhere in nifgen. Also there are session.py lists few values from this ring control not all.
![image](https://user-images.githubusercontent.com/30041511/32172327-36cfc2d0-bda1-11e7-9dc3-80e2a338724d.png)

AUX x/PFIx are missing from session.py
![image](https://user-images.githubusercontent.com/30041511/32172414-7f0955ca-bda1-11e7-93c8-6942414697d1.png)

**Comment by marcoskirsch** [comment]
In the configure_digital_edge_start_trigger case we don't want to use an enum for source. This is because the type is string, and the user is free to enter _any_ terminal on the system, which the routing subsystem will take care of resolving. If we use an enum, we'd be preventing the user from taking advantage of system-wide routing.
