### ISSUE TITLE
A bunch of nifgen enum still have values have prefix NIFGEN_

### ISSUE THREAD

**Issue by injaleea** [ni/nimi-python#595]
https://github.com/ni/nimi-python/blob/eccec49bafa048a58f2d16b7ca067dca7d17bafa/src/nifgen/metadata/enums.py#L568

Is there any reason why this is skipped in PR #569 .

**Comment by marcoskirsch** [comment]
We are changing the source metadata to keep all the prefixes (NIFGEN_VAL, NIFGEN_ATTR, niFgen_) and do the removals solely on nimi-python. The idea is to do the minimal amount of processing on extracted metadata and have as little policy as possible over there. This is in #584 

So this may have been a bug but we didn't fix it because we had #584 in the works anyway.
