### ISSUE TITLE
should we remove Get/SetAttributeViInt64 ?

### ISSUE THREAD

**Issue by injaleea** [ni/nimi-python#608]
As of now there is no attributes have ViIn64 type for nifgen.  we are not generating of Attributes of same type. 

So do we have to generate SetAttributeViInt64 and GetAttributeViInt64 method for nifgen ?

**Comment by marcoskirsch** [comment]
We don't have to generate dead code. So it's ok to remove those methods because it's trivial to do so.

A similar question arose about the corresponding classes in attributes.py. We decided not to worry about removing those because it requires condegenerator complexity and it was deemed to be the wrong tradeoff.

**Comment by marcoskirsch** [comment]
Fixed by #609
