### ISSUE TITLE
Remove NI-ModInst support from generator

### ISSUE THREAD

**Issue by Fladolcetta** [ni/nimi-python#676]
Remove NI-ModInst support from generator. Users on windows can use MAX to discover devices, or call lsni on Linux systems.

**Comment by texasaggie97** [comment]
MAX is not a replacement for NI-ModInst. NI-ModInst is used for programmatic device discovery and enumeration. MAX is for interactive discovery and renaming. Because there is no other way to get the installed devices programmatically, and most of the work has already been done, we are keeping NI-ModInst.

We can always reconsider this decision if circumstances change.
