### ISSUE TITLE
No function for 2 and 4 wire resistance measurement in nidmm.Function

### ISSUE THREAD

**Issue by WilyMongooseZero** [ni/nimi-python#756]
Measuring resistance is a pretty basic capability of the dmm modules, but the nidmm.Function library doesn't have a 2 or 4 wire resistance measurement function.

**Comment by marcoskirsch** [comment]
I'm guessing your IDE is filtering the enum values because they are prefixed with underscore.
See [here](http://nimi-python.readthedocs.io/en/0.7.0/nidmm/enums.html#nidmm.Function._2_WIRE_RES).

This is a problem we were tracking in #706 and #708 but it looks it fell through the cracks. My guess is we will manually name them`TWO_WIRE_RES` and `FOUR_WIRE_RES` or something similar.

In the meantime, use the enums as is with the knowledge that your code will be broken in a future release because of this fix.

Thanks and sorry for the pain!
