### ISSUE TITLE
Remove things from nidmm module that are for obsolete hardware or redundant

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#875]
These properties are supported by obsolete hardware only so we should remove from new Python nidmm API:

*    latency = _attributes.AttributeViInt32(1150034)
*    shunt_value = _attributes.AttributeViReal64(1150003)
*    def get_measurement_period(self):

Consider removing the following because they are of very limited use on PXI / PXIe since trigger lines are specified as active high (407x is EOL and 408x doesn't have a front panel connector):
*    meas_dest_slope = _attributes.AttributeEnum(_attributes.AttributeViInt32, enums.MeasurementDestinationSlope, 1150002)
*    sample_trigger_slope = _attributes.AttributeEnum(_attributes.AttributeViInt32, enums.SampleTrigSlope, 1150010)
*    trigger_slope = _attributes.AttributeEnum(_attributes.AttributeViInt32, enums.TriggerSlope, 1250334)

If they ever get re-added, we should reuse the enum. Source metadata specifies separate identical enums (we can fix source metadata too).

The following functions are simple wrappers around properties. Per our guidelines we are removing these low-value functions:

*    configure_ac_bandwidth(self, ac_minimum_frequency_hz, ac_maximum_frequency_hz)
*    configure_open_cable_comp_values(self, conductance, susceptance)
*    configure_power_line_frequency(self, power_line_frequency_hz)
*    configure_short_cable_comp_values(self, resistance, reactance)
*    gett_aperture_time_info(self)
*    get_auto_range_value(self)

**Comment by thofler** [comment]
> Consider removing the following because they are of very limited use on PXI / PXIe since trigger lines are specified as active high (407x is EOL and 408x doesn't have a front panel connector):
meas_dest_slope = _attributes.AttributeEnum(_attributes.AttributeViInt32, enums.MeasurementDestinationSlope, 1150002)
sample_trigger_slope = _attributes.AttributeEnum(_attributes.AttributeViInt32, enums.SampleTrigSlope, 1150010)
trigger_slope = _attributes.AttributeEnum(_attributes.AttributeViInt32, enums.TriggerSlope, 1250334)

The 407x defaults to active low while most other modules default to active high.
So the trigger slope properties are the only way to make 407x work well with other modules.

As a workaround, we are using _set_attribute_vi_int32 since trigger_slope was removed from the API:
`nidmm_trigger_slope_attribute_id = 1250334`
`nidmm_trigger_slope_rising_edge = 0`
`dmm._set_attribute_vi_int32(nidmm_trigger_slope_attribute_id, nidmm_trigger_slope_rising_edge)`
