### ISSUE TITLE
Classes with dynamic members are user-hostile and maintenance-hostile

### ISSUE THREAD

**Issue by epage** [ni/nimi-python#934]
Example: WaveformInfo from https://github.com/ni/nimi-python/pull/933

User Problem
- Users can't rely on the code or documentation in front of them to know what they can access
- IDE's can't auto-complete
- mypy will complain

Maintenance problems
- The intent of the code is less clear, making it more likely someone will break it when changing it.

**Comment by texasaggie97** [comment]
Documentation is already correct for these members - See return info in https://nimi-python.readthedocs.io/en/master/niscope/class.html#niscope.Session.fetch

**Comment by marcoskirsch** [comment]
> Classes with dynamic members are user-hostile and maintenance-hostile #934

Are there examples other than `WaveformInfo`?
IIRC the only reason this class has dynamic members is because of Python 2.7 limitations. Outside of dropping Python 2.7, what would you suggest?

**Comment by epage** [comment]
How is this coupled to Python 2.7?

#935 implements exactly what I'd expect.

**Comment by texasaggie97** [comment]
`WaveformInfo` ended up being the only "custom type" needed.

The dynamic-ness comes from not Python 2.7, but because we decided to add `channel`, `record` and `samples` to each `WaveformInfo` instead of requiring the user to parse out the portion of the 1D array coming back from the driver that applies to this channel and record.

What you are thinking about regarding Python 2.7 is how `samples` is added. In Python 3+ it is a `memoryview` of the 1D array from the driver to avoid copies. In Python 2.7, `memoryview` doesn't support arrays so we have to create an `array.array` for each `WaveformInfo` by copying the samples from the 1D array in to a new one.
